In [2]:
import numpy as np

In [3]:
a = np.array([[1],[2],[3]])
b = np.array([[2],[3],[4]])

a, b

(array([[1],
        [2],
        [3]]),
 array([[2],
        [3],
        [4]]))

In [5]:
c = np.hstack((a,b))
c

array([[1, 2],
       [2, 3],
       [3, 4]])

In [7]:
e = [6, 7, 8]
f = [4, 5, 6]
e, f

([6, 7, 8], [4, 5, 6])

In [9]:
z = np.hstack((e,f))
z

array([6, 7, 8, 4, 5, 6])